### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by tyrope** [jjclark1982/bitburner-scripts#1]
I wanted to implement https://github.com/jjclark1982/bitburner-scripts/blob/main/hacking/batch-view.js into my bitburner scripts; but given they're synced via github I'd have to redistribute; since you have no license file in your repo I can't legally do that. (since you own exclusive rights to any program you write)

In the spirit of open source, could you add a license to your repository? GitHub has a tool to help you with that!

**Comment by jjclark1982** [comment]
Thanks. I have added a permissive license.
