### ISSUE TITLE
AugmentationNames export does not exist 

### ISSUE THREAD

**Issue by ccheath** [jjclark1982/bitburner-scripts#8]
in the inspect/get-info.js file there is an import of AugmentationNames from augmentations/info.js but there is no export named AugmentationNames in that file.

**Comment by jjclark1982** [comment]
Thanks, I've fixed the import name in info.js.

Autocomplete doesn't work very well with values that include spaces. That and some other potential improvements are discussed here: https://github.com/bitburner-official/bitburner-src/issues/522
